[tool.poetry]
name = "pyscatt"
version = "0.1.0"
description = ""
authors = ["Michael Whapples <mwhapples@aim.com>"]

[tool.poetry.dependencies]
python = "^3.9"
comtypes = "^1.1.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pyinstaller = "^4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
